site_name: Java Tron
site_url: https://tronprotocol.github.io/documentation-zh/
repo_url: https://github.com/tronprotocol/documentation-zh

nav:
    - 入门: 
        - Java-tron入门: getting_started/getting_started_with_javatron.md
    - 使用Java-tron:
        - 部署Java-tron: using_javatron/installing_javatron.md
        - 备份和恢复: using_javatron/backup_restore.md
        - 轻节点: developers/litefullnode.md
        - 私链网络: using_javatron/private_network.md
        - 事件插件: architecture/event.md
        - 数据库配置: architecture/database.md
        - 网络配置: using_javatron/connecting_to_tron.md
        - 节点监控: using_javatron/metrics.md
        - 工具:
            - 数据库迁移: using_javatron/toolkit.md
    - API 接口:
        - HTTP 接口: api/http.md
        - gRPC 接口: api/rpc.md
    - 核心协议:
        - 波场共识: introduction/dpos.md
        - 超级代表: mechanism-algorithm/sr.md
        - 账户模型: mechanism-algorithm/account.md
        - 资源模型: mechanism-algorithm/resource.md
        - 智能合约: contracts/contract.md
        - 去中心化交易所: mechanism-algorithm/dex.md
        - 多重签名: mechanism-algorithm/multi-signatures.md
    - Java-tron开发:
        - 开发者指南: developers/java-tron.md
        - TIPs工作流程: developers/tips.md
        - Issue工作流程: developers/issue-workflow.md
        - 配置IDE开发环境: developers/run-in-idea.md
        - 开发示例: developers/demo.md
        - GPG Key: developers/gpg.md
    - Dapp开发:
        - Dapp开发工具: contracts/compiler.md
    - Wallet-cli: 
        - 安装: clients/wallet-cli.md
    - 版本发布:
        - 一致性检验: releases/index.md
    - 术语表: glossary.md


theme: readthedocs
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - footnotes
    - codehilite
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.tilde
    - pymdownx.tasklist
    - pymdownx.superfences
